version = 1

#[install.comfyui-scripts]
#store-path = "/nix/store/nn87081h4ny2xkqnp3f48j8nqvb3wrj5-comfyui-scripts-0.9.0"

[install.python3]
pkg-path = "python311"

[install.uv]
pkg-path = "uv"

[vars]
COMFYUI_SERVE_HOST = "0.0.0.0"
COMFYUI_SERVE_PORT = "3000"

[hook]
on-activate = """
export COMFYUI_WATCH_DIR="${COMFYUI_WATCH_DIR:-$FLOX_ENV_CACHE/watch}"
"""

[services.comfyui-watch]
command = "comfyui-watch"
is-daemon = false

[services.comfyui-api]
command = "comfyui-serve"
is-daemon = false

[profile]
